Self-assessment: I felt pretty confident with this week's exercises as they were quite straightforward. I only had a bit of initial trouble with writing the function in exercise 6.6 but figured it out relatively quickly after a bit of trial and error.

# 6.3 What Does This Code Do?

The code below first creates a dictionary called `temperatures` which contains three separate Fahrenheit temperatures for each of four days (Monday through Thursday). The `for` statement specifically will iterate through `temperature`'s key-value pairs and print out the keys of this dictionary with `k` and then printing the average of each keys' values with `v`. The `items()` method also allows us to return each key-value pair as a tuple. Each of the temperatures will have 2 decimal points as well. 

In [66]:
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}

for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')

Monday: 70.00
Tuesday: 56.67
Wednesday: 79.33
Thursday: 74.00


# 6.6 Data Science: Duplicate Word Removal

In [67]:
def ordered_unique(word_list):
    """Receives a list of words, then displays only unique words in alphabetical order."""
    same_case_list = []
    for i in range(len(word_list)):
        same_case_list.append(word_list[i].upper()) # Creates a new list with all words in the same uppercase
    unique_words = set(same_case_list) # Changes the list to a set to get the unique words only
    final_list = list(unique_words) # Change the set back to a list so we can sort the words alphabetically
    final_list.sort() # Uses the 'sort' function to get words in alphabetical order
    for word in final_list:
        print(word, end=' ')

words = ['Apple', 'apple', 'cat', 'DOG', 'Banana']

ordered_unique(words)

APPLE BANANA CAT DOG 

# 6.9 Dictionary Manipulations

In [68]:
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}

In [69]:
'Canada' in tlds # Part (a) 

True

In [70]:
'France' in tlds # Part (b) 

False

In [71]:
print(f'{"Country":>13}{"Code":>10}') # Part (c) 
for country, code in tlds.items():
    print(f'{country:>13}{code:>10}')

      Country      Code
       Canada        ca
United States        us
       Mexico        mx


In [72]:
tlds['Sweden'] = 'sw' # Part (d)
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'sw'}

In [73]:
tlds['Sweden'] = 'se' # Part (e)
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'se'}

In [74]:
reverse_tlds = {code: country for country, code in tlds.items()} # Part (f)
reverse_tlds

{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

In [75]:
uppercase_tlds = {code: country.upper() for code, country in reverse_tlds.items()} # Part (g)
uppercase_tlds

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

# 7.2 Broadcasting

In [76]:
import numpy as np

original = np.arange(4).reshape(2, 2) # Create the original array to operate on

In [77]:
original ** 3 # Part (a)

array([[ 0,  1],
       [ 8, 27]], dtype=int32)

In [78]:
original + 7 # Part (b)

array([[ 7,  8],
       [ 9, 10]])

In [79]:
original * 2 # Part (c)

array([[0, 2],
       [4, 6]])

# 7.3 Element-Wise `array` Multiplication

In [80]:
import numpy as np

first_array = np.arange(2, 19, 2).reshape(3, 3)
second_array = np.arange(9, 0, -1).reshape(3, 3)

first_array * second_array

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

# 7.9 Data Science: Indexing and Slicing `arrays`

In [81]:
import numpy as np

the_array = np.arange(1, 16).reshape(3, 5)
the_array # Show the original array to make it easier to slice/index below

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [82]:
the_array[2] # Part (a) selecting row 2

array([11, 12, 13, 14, 15])

In [83]:
the_array[:, -1] # Part (b) selecting column 5

array([ 5, 10, 15])

In [84]:
the_array[0:2] # Part (c) selecting rows 0 and 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [85]:
the_array[:, 2:4] # Part (d) selecting columns 2-4

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [86]:
the_array[0, 3] # Part (e) selecting the element in the first row and fourth column

4

In [87]:
the_array[1:3, [0, 2, 4]] # Part (f) selecting elements from rows 1 and 2 in columns 0, 2 and 4

array([[ 6,  8, 10],
       [11, 13, 15]])

# 7.14 Data Science: Horizontal and Vertical Stacking

In [88]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]]) # Create original arrays for stacking

In [89]:
array3 = np.vstack((array1, array2)) # Part (a) to create a 4-by-2 array
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [90]:
array4 = np.hstack((array1, array2)) # Part (b) to create a 2-by-4 array
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [91]:
array5 = np.vstack((array4, array4)) # Part (c) to create a 4-by-4 array
array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [92]:
array6 = np.hstack((array3, array3)) # Part (d) to create a 4-by-4 array
array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])